name: Sync Channels
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run sync
      - uses: stefanzweifel/git-auto-commit-action@v5
